export const TODO_CONST_ACTIONS = {
  CREATE_TODO: 'CREATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  SEND_EACH_ID_TODO: 'SEND_EACH_ID_TODO',
  SELECT_COMPLETE_TODO: 'SELECT_COMPLETE_TODO',
  SELECT_INCOMPLETE_TODO: 'SELECT_INCOMPLETE_TODO',
};
